version: '3.7'
services:
    sqlserver1:
        build: 
          context: .
          dockerfile: dockerfile
        ports:  
          - "15789:1433"
        env_file:
          - ACCEPT_EULA=Y
          - MSSQL_DATA_DIR=/var/opt/sqlserver/data
          - MSSQL_LOG_DIR=/var/opt/sqlserver/log
          - MSSQL_BACKUP_DIR=/var/opt/sqlserver/backup
          - MSSQL_SA_PASSWORD=Testing1122
        volumes: 
          - sqlsystem:/var/opt/mssql/
          - sqldata:/var/opt/sqlserver/data
          - sqllog:/var/opt/sqlserver/log
          - sqlbackup:/var/opt/sqlserver/backup
volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup: