version: '3.7'
services:
  dev-environment:
    build: 
      context: .
      dockerfile: .devcontainer/dockerfile
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - .:/workspace

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
  ms_server:
      container_name: "msql_server"
      build: 
        context: .
        dockerfile: MS_SQL_AW/dockerfile
      ports:  
        - "5000-5005:1433"
  jenkins:
      container_name: "jenkins"
      image: jenkins/jenkins:lts
      ports: 
        - "8080:8080"
        - "50000:50000"
